#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaLeaderboardTab

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonInput_structs.hpp"
#include "FortniteUI_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.Init Back Action
// 0x0020 (0x0020 - 0x0000)
struct AthenaLeaderboardTab_C_Init_Back_Action final
{
public:
	class UCommonInputSubsystem*                  CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool* bPassThrough)>           K2Node_CreateDelegate_OutputDelegate;              // 0x000C(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasInputActionHandler_ReturnValue;        // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_Init_Back_Action) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_Init_Back_Action");
static_assert(sizeof(AthenaLeaderboardTab_C_Init_Back_Action) == 0x000020, "Wrong size on AthenaLeaderboardTab_C_Init_Back_Action");
static_assert(offsetof(AthenaLeaderboardTab_C_Init_Back_Action, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000000, "Member 'AthenaLeaderboardTab_C_Init_Back_Action::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_Init_Back_Action, CallFunc_GetCurrentInputType_ReturnValue) == 0x000008, "Member 'AthenaLeaderboardTab_C_Init_Back_Action::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_Init_Back_Action, K2Node_CreateDelegate_OutputDelegate) == 0x00000C, "Member 'AthenaLeaderboardTab_C_Init_Back_Action::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_Init_Back_Action, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00001C, "Member 'AthenaLeaderboardTab_C_Init_Back_Action::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_Init_Back_Action, CallFunc_HasInputActionHandler_ReturnValue) == 0x00001D, "Member 'AthenaLeaderboardTab_C_Init_Back_Action::CallFunc_HasInputActionHandler_ReturnValue' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.HandleBackAction
// 0x0001 (0x0001 - 0x0000)
struct AthenaLeaderboardTab_C_HandleBackAction final
{
public:
	bool                                          PassThrough;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_HandleBackAction) == 0x000001, "Wrong alignment on AthenaLeaderboardTab_C_HandleBackAction");
static_assert(sizeof(AthenaLeaderboardTab_C_HandleBackAction) == 0x000001, "Wrong size on AthenaLeaderboardTab_C_HandleBackAction");
static_assert(offsetof(AthenaLeaderboardTab_C_HandleBackAction, PassThrough) == 0x000000, "Member 'AthenaLeaderboardTab_C_HandleBackAction::PassThrough' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.ToggleDisabledTabVisuals
// 0x0002 (0x0002 - 0x0000)
struct AthenaLeaderboardTab_C_ToggleDisabledTabVisuals final
{
public:
	bool                                          bShouldBeDisabled;                                 // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_ToggleDisabledTabVisuals) == 0x000001, "Wrong alignment on AthenaLeaderboardTab_C_ToggleDisabledTabVisuals");
static_assert(sizeof(AthenaLeaderboardTab_C_ToggleDisabledTabVisuals) == 0x000002, "Wrong size on AthenaLeaderboardTab_C_ToggleDisabledTabVisuals");
static_assert(offsetof(AthenaLeaderboardTab_C_ToggleDisabledTabVisuals, bShouldBeDisabled) == 0x000000, "Member 'AthenaLeaderboardTab_C_ToggleDisabledTabVisuals::bShouldBeDisabled' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ToggleDisabledTabVisuals, CallFunc_Not_PreBool_ReturnValue) == 0x000001, "Member 'AthenaLeaderboardTab_C_ToggleDisabledTabVisuals::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnQueryStateChanged
// 0x0020 (0x0020 - 0x0000)
struct AthenaLeaderboardTab_C_OnQueryStateChanged final
{
public:
	bool                                          bQueryInProgress;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue; // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3[0x1];                                        // 0x0003(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0018(0x0008)(NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnQueryStateChanged) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnQueryStateChanged");
static_assert(sizeof(AthenaLeaderboardTab_C_OnQueryStateChanged) == 0x000020, "Wrong size on AthenaLeaderboardTab_C_OnQueryStateChanged");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, bQueryInProgress) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::bQueryInProgress' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, CallFunc_Not_PreBool_ReturnValue) == 0x000001, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue) == 0x000002, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, CallFunc_BooleanAND_ReturnValue) == 0x000014, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnQueryStateChanged, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000018, "Member 'AthenaLeaderboardTab_C_OnQueryStateChanged::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnFriendTypeChangeGamepad
// 0x0028 (0x0028 - 0x0000)
struct AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad final
{
public:
	bool                                          bCommitted;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaRotator_C*                       K2Node_DynamicCast_AsAthena_Rotator;               // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad");
static_assert(sizeof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad) == 0x000028, "Wrong size on AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, bCommitted) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::bCommitted' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, CallFunc_GetCurrentInputType_ReturnValue) == 0x000010, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, K2Node_DynamicCast_AsAthena_Rotator) == 0x000018, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::K2Node_DynamicCast_AsAthena_Rotator' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000021, "Member 'AthenaLeaderboardTab_C_OnFriendTypeChangeGamepad::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnPlaylistChangeGamepad
// 0x0028 (0x0028 - 0x0000)
struct AthenaLeaderboardTab_C_OnPlaylistChangeGamepad final
{
public:
	bool                                          bCommitted;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonInputSubsystem*                  CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              CallFunc_GetCurrentInputType_ReturnValue;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaRotator_C*                       K2Node_DynamicCast_AsAthena_Rotator;               // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnPlaylistChangeGamepad");
static_assert(sizeof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad) == 0x000028, "Wrong size on AthenaLeaderboardTab_C_OnPlaylistChangeGamepad");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, bCommitted) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::bCommitted' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, CallFunc_GetCurrentInputType_ReturnValue) == 0x000010, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::CallFunc_GetCurrentInputType_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000011, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, K2Node_DynamicCast_AsAthena_Rotator) == 0x000018, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::K2Node_DynamicCast_AsAthena_Rotator' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnPlaylistChangeGamepad, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'AthenaLeaderboardTab_C_OnPlaylistChangeGamepad::K2Node_DynamicCast_bSuccess' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__SecondaryTabList_K2Node_ComponentBoundEvent_189_OnTabButtonCreated__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__SecondaryTabList_K2Node_ComponentBoundEvent_189_OnTabButtonCreated__DelegateSignature final
{
public:
	class FName                                   TabId;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButton*                          TabButton;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__SecondaryTabList_K2Node_ComponentBoundEvent_189_OnTabButtonCreated__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__SecondaryTabList_K2Node_ComponentBoundEvent_189_OnTabButtonCreated__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__SecondaryTabList_K2Node_ComponentBoundEvent_189_OnTabButtonCreated__DelegateSignature) == 0x000010, "Wrong size on AthenaLeaderboardTab_C_BndEvt__SecondaryTabList_K2Node_ComponentBoundEvent_189_OnTabButtonCreated__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__SecondaryTabList_K2Node_ComponentBoundEvent_189_OnTabButtonCreated__DelegateSignature, TabId) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__SecondaryTabList_K2Node_ComponentBoundEvent_189_OnTabButtonCreated__DelegateSignature::TabId' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__SecondaryTabList_K2Node_ComponentBoundEvent_189_OnTabButtonCreated__DelegateSignature, TabButton) == 0x000008, "Member 'AthenaLeaderboardTab_C_BndEvt__SecondaryTabList_K2Node_ComponentBoundEvent_189_OnTabButtonCreated__DelegateSignature::TabButton' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature final
{
public:
	class UWidget*                                ActiveWidget;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         ActiveWidgetIndex;                                 // 0x0008(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature) == 0x000010, "Wrong size on AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature, ActiveWidget) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature::ActiveWidget' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature, ActiveWidgetIndex) == 0x000008, "Member 'AthenaLeaderboardTab_C_BndEvt__LeaderboardSwitcher_K2Node_ComponentBoundEvent_17_OnActiveWidgetChanged__DelegateSignature::ActiveWidgetIndex' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature final
{
public:
	int32                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature) == 0x000004, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature) == 0x000004, "Wrong size on AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature, Value) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__MatchRotator_K2Node_ComponentBoundEvent_39_OnRotated__DelegateSignature::Value' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature
// 0x0004 (0x0004 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature final
{
public:
	int32                                         Value;                                             // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature) == 0x000004, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature) == 0x000004, "Wrong size on AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature, Value) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__FriendsRotator_K2Node_ComponentBoundEvent_63_OnRotated__DelegateSignature::Value' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_57_OnTabButtonRemoved__DelegateSignature
// 0x0010 (0x0010 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_57_OnTabButtonRemoved__DelegateSignature final
{
public:
	class FName                                   TabId;                                             // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButton*                          TabButton;                                         // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_57_OnTabButtonRemoved__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_57_OnTabButtonRemoved__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_57_OnTabButtonRemoved__DelegateSignature) == 0x000010, "Wrong size on AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_57_OnTabButtonRemoved__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_57_OnTabButtonRemoved__DelegateSignature, TabId) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_57_OnTabButtonRemoved__DelegateSignature::TabId' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_57_OnTabButtonRemoved__DelegateSignature, TabButton) == 0x000008, "Member 'AthenaLeaderboardTab_C_BndEvt__LeaderboardTabList_K2Node_ComponentBoundEvent_57_OnTabButtonRemoved__DelegateSignature::TabButton' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnUpdateTabButtonText
// 0x0058 (0x0058 - 0x0000)
struct AthenaLeaderboardTab_C_OnUpdateTabButtonText final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAthenaPlaylistLeaderboardData         PlaylistTabData;                                   // 0x0008(0x0050)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnUpdateTabButtonText) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnUpdateTabButtonText");
static_assert(sizeof(AthenaLeaderboardTab_C_OnUpdateTabButtonText) == 0x000058, "Wrong size on AthenaLeaderboardTab_C_OnUpdateTabButtonText");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateTabButtonText, Button) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnUpdateTabButtonText::Button' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateTabButtonText, PlaylistTabData) == 0x000008, "Member 'AthenaLeaderboardTab_C_OnUpdateTabButtonText::PlaylistTabData' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnUpdateLeaderboardListUI
// 0x0028 (0x0028 - 0x0000)
struct AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI final
{
public:
	bool                                          bWasSuccessful;                                    // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortLeaderboardRowProxyInstance*       LocalUserRow_0;                                    // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   QueryErrorStr;                                     // 0x0010(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI");
static_assert(sizeof(AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI) == 0x000028, "Wrong size on AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI, bWasSuccessful) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI::bWasSuccessful' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI, LocalUserRow_0) == 0x000008, "Member 'AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI::LocalUserRow_0' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI, QueryErrorStr) == 0x000010, "Member 'AthenaLeaderboardTab_C_OnUpdateLeaderboardListUI::QueryErrorStr' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnUpdateListHeader
// 0x0050 (0x0050 - 0x0000)
struct AthenaLeaderboardTab_C_OnUpdateListHeader final
{
public:
	struct FAthenaPlaylistLeaderboardData         PlaylistTabData;                                   // 0x0000(0x0050)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnUpdateListHeader) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_OnUpdateListHeader");
static_assert(sizeof(AthenaLeaderboardTab_C_OnUpdateListHeader) == 0x000050, "Wrong size on AthenaLeaderboardTab_C_OnUpdateListHeader");
static_assert(offsetof(AthenaLeaderboardTab_C_OnUpdateListHeader, PlaylistTabData) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnUpdateListHeader::PlaylistTabData' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.OnInputMethodChanged_Event_0
// 0x0001 (0x0001 - 0x0000)
struct AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0 final
{
public:
	ECommonInputType                              bNewInputType;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0) == 0x000001, "Wrong alignment on AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0");
static_assert(sizeof(AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0) == 0x000001, "Wrong size on AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0");
static_assert(offsetof(AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0, bNewInputType) == 0x000000, "Member 'AthenaLeaderboardTab_C_OnInputMethodChanged_Event_0::bNewInputType' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__MobileCloseButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__MobileCloseButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__MobileCloseButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__MobileCloseButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__MobileCloseButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on AthenaLeaderboardTab_C_BndEvt__MobileCloseButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__MobileCloseButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__MobileCloseButton_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.BndEvt__MobileCloseButton2_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct AthenaLeaderboardTab_C_BndEvt__MobileCloseButton2_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_BndEvt__MobileCloseButton2_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_BndEvt__MobileCloseButton2_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(AthenaLeaderboardTab_C_BndEvt__MobileCloseButton2_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on AthenaLeaderboardTab_C_BndEvt__MobileCloseButton2_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(AthenaLeaderboardTab_C_BndEvt__MobileCloseButton2_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'AthenaLeaderboardTab_C_BndEvt__MobileCloseButton2_K2Node_ComponentBoundEvent_1_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function AthenaLeaderboardTab.AthenaLeaderboardTab_C.ExecuteUbergraph_AthenaLeaderboardTab
// 0x0218 (0x0218 - 0x0000)
struct AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button;                 // 0x0008(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0013(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_1;                              // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0015(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_4;                              // 0x0016(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_17[0x1];                                       // 0x0017(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortLeaderboardContext*                CallFunc_GetContext_ReturnValue;                   // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_CanShowGlobalLeaderboards_ReturnValue;    // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_5;                              // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_6;                              // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0024(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_7;                              // 0x0025(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0026(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_8;                              // 0x0027(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonInputSubsystem*                  CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_4;                              // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(ECommonInputType bNewInputType)> K2Node_CreateDelegate_OutputDelegate;              // 0x0034(0x0010)(ZeroConstructor, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_9;                              // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_10;                             // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_46[0x2];                                       // 0x0046(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_ComponentBoundEvent_TabId_1;                // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButton*                          K2Node_ComponentBoundEvent_TabButton_1;            // 0x0050(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UWidget*                                K2Node_ComponentBoundEvent_ActiveWidget;           // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_ActiveWidgetIndex;      // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Value_1;                // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_ComponentBoundEvent_Value;                  // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FName                                   K2Node_ComponentBoundEvent_TabId;                  // 0x006C(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButton*                          K2Node_ComponentBoundEvent_TabButton;              // 0x0078(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Map_Remove_ReturnValue;                   // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButton*                          K2Node_Event_Button;                               // 0x0088(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FAthenaPlaylistLeaderboardData         K2Node_Event_PlaylistTabData_1;                    // 0x0090(0x0050)(ConstParm)
	bool                                          K2Node_Event_bWasSuccessful;                       // 0x00E0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E1[0x7];                                       // 0x00E1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortLeaderboardRowProxyInstance*       K2Node_Event_LocalUserRow;                         // 0x00E8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   K2Node_Event_QueryErrorStr;                        // 0x00F0(0x0018)(ConstParm)
	class FText                                   CallFunc_TextToUpper_ReturnValue;                  // 0x0108(0x0018)()
	bool                                          CallFunc_NotEqual_IntInt_ReturnValue;              // 0x0120(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x0121(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_122[0x6];                                      // 0x0122(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaLeaderboardTabButton_C*          K2Node_DynamicCast_AsAthena_Leaderboard_Tab_Button; // 0x0128(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0130(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_11;                             // 0x0131(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_132[0x6];                                      // 0x0132(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAthenaPlaylistLeaderboardData         K2Node_Event_PlaylistTabData;                      // 0x0138(0x0050)(ConstParm)
	TDelegate<void(bool* bPassThrough)>           K2Node_CreateDelegate_OutputDelegate_1;            // 0x0188(0x0010)(ZeroConstructor, NoDestructor)
	TDelegate<void(bool* bPassThrough)>           K2Node_CreateDelegate_OutputDelegate_2;            // 0x0198(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable_5;                              // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_2;                           // 0x01A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue; // 0x01AA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_12;                             // 0x01AB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x01AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x01B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_3;                           // 0x01B1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01B2(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x01B3(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default_4;                           // 0x01B4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SelectTabByID_ReturnValue;                // 0x01B5(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable_13;                             // 0x01B6(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B7[0x1];                                      // 0x01B7(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaRotator_C*                       K2Node_DynamicCast_AsAthena_Rotator;               // 0x01B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x01C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C1[0x7];                                      // 0x01C1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAthenaRotator_C*                       K2Node_DynamicCast_AsAthena_Rotator_1;             // 0x01C8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x01D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_6;                              // 0x01D1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D2[0x6];                                      // 0x01D2(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortLeaderboardContext*                CallFunc_GetContext_ReturnValue_1;                 // 0x01D8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortFrontEndContext*                   CallFunc_GetContext_ReturnValue_2;                 // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanShowLeaderboards_ReturnValue;          // 0x01E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E9[0x7];                                      // 0x01E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortLeaderboardContext*                CallFunc_GetContext_ReturnValue_3;                 // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_5;                           // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanShowLeaderboards_ReturnValue_1;        // 0x01F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HandleBackAction_PassThrough;             // 0x01FA(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsMobileGame_ReturnValue;                 // 0x01FB(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	int32                                         Temp_int_Variable;                                 // 0x01FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_6;                           // 0x0200(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMobileGame_ReturnValue_1;               // 0x0201(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_202[0x2];                                      // 0x0202(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Variable_1;                               // 0x0204(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ECommonInputType                              K2Node_CustomEvent_bNewInputType;                  // 0x0208(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_7;                              // 0x0209(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_20A[0x2];                                      // 0x020A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         K2Node_Select_Default_7;                           // 0x020C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button_1;               // 0x0210(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab) == 0x000008, "Wrong alignment on AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab");
static_assert(sizeof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab) == 0x000218, "Wrong size on AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, EntryPoint) == 0x000000, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::EntryPoint' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_Button) == 0x000008, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable) == 0x000010, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable) == 0x000011, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_1) == 0x000012, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_2) == 0x000013, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_1) == 0x000014, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_3) == 0x000015, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_4) == 0x000016, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetContext_ReturnValue) == 0x000018, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_2) == 0x000020, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_CanShowGlobalLeaderboards_ReturnValue) == 0x000021, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_CanShowGlobalLeaderboards_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_5) == 0x000022, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_5' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_6) == 0x000023, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_6' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_3) == 0x000024, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_7) == 0x000025, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_7' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default) == 0x000026, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_8) == 0x000027, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_8' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000028, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_4) == 0x000030, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_CreateDelegate_OutputDelegate) == 0x000034, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_9) == 0x000044, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_9' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_10) == 0x000045, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_10' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_TabId_1) == 0x000048, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_TabId_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_TabButton_1) == 0x000050, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_TabButton_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_ActiveWidget) == 0x000058, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_ActiveWidget' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_ActiveWidgetIndex) == 0x000060, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_ActiveWidgetIndex' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_Value_1) == 0x000064, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_Value_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_Value) == 0x000068, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_Value' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_TabId) == 0x00006C, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_TabId' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_TabButton) == 0x000078, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_TabButton' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_Map_Remove_ReturnValue) == 0x000080, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_Map_Remove_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_Button) == 0x000088, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_Button' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_PlaylistTabData_1) == 0x000090, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_PlaylistTabData_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_bWasSuccessful) == 0x0000E0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_bWasSuccessful' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_LocalUserRow) == 0x0000E8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_LocalUserRow' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_QueryErrorStr) == 0x0000F0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_QueryErrorStr' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_TextToUpper_ReturnValue) == 0x000108, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_TextToUpper_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_NotEqual_IntInt_ReturnValue) == 0x000120, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_NotEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_1) == 0x000121, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_DynamicCast_AsAthena_Leaderboard_Tab_Button) == 0x000128, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_DynamicCast_AsAthena_Leaderboard_Tab_Button' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_DynamicCast_bSuccess) == 0x000130, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_11) == 0x000131, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_11' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Event_PlaylistTabData) == 0x000138, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Event_PlaylistTabData' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_CreateDelegate_OutputDelegate_1) == 0x000188, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_CreateDelegate_OutputDelegate_2) == 0x000198, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_5) == 0x0001A8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_5' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_2) == 0x0001A9, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue) == 0x0001AA, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_CanShowFriendsOnlyLeaderboard_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_12) == 0x0001AB, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_12' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_Array_Length_ReturnValue) == 0x0001AC, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_Greater_IntInt_ReturnValue) == 0x0001B0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_3) == 0x0001B1, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_BooleanAND_ReturnValue) == 0x0001B2, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_BooleanAND_ReturnValue_1) == 0x0001B3, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_4) == 0x0001B4, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_4' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_SelectTabByID_ReturnValue) == 0x0001B5, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_SelectTabByID_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_byte_Variable_13) == 0x0001B6, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_byte_Variable_13' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_DynamicCast_AsAthena_Rotator) == 0x0001B8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_DynamicCast_AsAthena_Rotator' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_DynamicCast_bSuccess_1) == 0x0001C0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_DynamicCast_AsAthena_Rotator_1) == 0x0001C8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_DynamicCast_AsAthena_Rotator_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_DynamicCast_bSuccess_2) == 0x0001D0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_6) == 0x0001D1, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_6' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetContext_ReturnValue_1) == 0x0001D8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetContext_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetContext_ReturnValue_2) == 0x0001E0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetContext_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_CanShowLeaderboards_ReturnValue) == 0x0001E8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_CanShowLeaderboards_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_GetContext_ReturnValue_3) == 0x0001F0, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_GetContext_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_5) == 0x0001F8, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_5' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_CanShowLeaderboards_ReturnValue_1) == 0x0001F9, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_CanShowLeaderboards_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_HandleBackAction_PassThrough) == 0x0001FA, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_HandleBackAction_PassThrough' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_IsMobileGame_ReturnValue) == 0x0001FB, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_IsMobileGame_ReturnValue' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_int_Variable) == 0x0001FC, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_6) == 0x000200, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_6' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, CallFunc_IsMobileGame_ReturnValue_1) == 0x000201, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::CallFunc_IsMobileGame_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_int_Variable_1) == 0x000204, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_int_Variable_1' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_CustomEvent_bNewInputType) == 0x000208, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_CustomEvent_bNewInputType' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, Temp_bool_Variable_7) == 0x000209, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::Temp_bool_Variable_7' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_Select_Default_7) == 0x00020C, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_Select_Default_7' has a wrong offset!");
static_assert(offsetof(AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab, K2Node_ComponentBoundEvent_Button_1) == 0x000210, "Member 'AthenaLeaderboardTab_C_ExecuteUbergraph_AthenaLeaderboardTab::K2Node_ComponentBoundEvent_Button_1' has a wrong offset!");

}

