#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_JollyRascal_Athena

#include "Basic.hpp"

#include "B_ConsumableSmall_Athena_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_JollyRascal_Athena.B_JollyRascal_Athena_C
// 0x0008 (0x0950 - 0x0948)
class AB_JollyRascal_Athena_C final : public AB_ConsumableSmall_Athena_C
{
public:
	class UStaticMeshComponent*                   JollyRascal;                                       // 0x0948(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_JollyRascal_Athena_C">();
	}
	static class AB_JollyRascal_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_JollyRascal_Athena_C>();
	}
};
static_assert(alignof(AB_JollyRascal_Athena_C) == 0x000008, "Wrong alignment on AB_JollyRascal_Athena_C");
static_assert(sizeof(AB_JollyRascal_Athena_C) == 0x000950, "Wrong size on AB_JollyRascal_Athena_C");
static_assert(offsetof(AB_JollyRascal_Athena_C, JollyRascal) == 0x000948, "Member 'AB_JollyRascal_Athena_C::JollyRascal' has a wrong offset!");

}

