#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Prj_Bullet_Sniper_Heavy

#include "Basic.hpp"

#include "B_Prj_Bullet_Sniper_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Prj_Bullet_Sniper_Heavy.B_Prj_Bullet_Sniper_Heavy_C
// 0x0000 (0x0880 - 0x0880)
class AB_Prj_Bullet_Sniper_Heavy_C final : public AB_Prj_Bullet_Sniper_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Prj_Bullet_Sniper_Heavy_C">();
	}
	static class AB_Prj_Bullet_Sniper_Heavy_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Prj_Bullet_Sniper_Heavy_C>();
	}
};
static_assert(alignof(AB_Prj_Bullet_Sniper_Heavy_C) == 0x000008, "Wrong alignment on AB_Prj_Bullet_Sniper_Heavy_C");
static_assert(sizeof(AB_Prj_Bullet_Sniper_Heavy_C) == 0x000880, "Wrong size on AB_Prj_Bullet_Sniper_Heavy_C");

}

