#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_XL_Jog_N_Shake

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_XL_Jog_N_Shake.BP_XL_Jog_N_Shake_C
// 0x0000 (0x0160 - 0x0160)
class UBP_XL_Jog_N_Shake_C final : public UCameraShake
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_XL_Jog_N_Shake_C">();
	}
	static class UBP_XL_Jog_N_Shake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_XL_Jog_N_Shake_C>();
	}
};
static_assert(alignof(UBP_XL_Jog_N_Shake_C) == 0x000008, "Wrong alignment on UBP_XL_Jog_N_Shake_C");
static_assert(sizeof(UBP_XL_Jog_N_Shake_C) == 0x000160, "Wrong size on UBP_XL_Jog_N_Shake_C");

}

