#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Trap_ZippyTrout

#include "Basic.hpp"

#include "GameplayTags_structs.hpp"
#include "Engine_structs.hpp"
#include "GA_TrapGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Trap_ZippyTrout.GA_Trap_ZippyTrout_C
// 0x0010 (0x09A0 - 0x0990)
class UGA_Trap_ZippyTrout_C final : public UGA_TrapGeneric_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Trap_ZippyTrout_C;               // 0x0990(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FGameplayTag                           Tag;                                               // 0x0998(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Trap_ZippyTrout(int32 EntryPoint);
	void Cancelled_DE7AFBFE4CD1F3C98F2AFEB41FBFC13F(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void FX(const struct FGameplayCueParameters& NewParam);
	void Targeted_DE7AFBFE4CD1F3C98F2AFEB41FBFC13F(const struct FGameplayAbilityTargetDataHandle& TargetData, const struct FGameplayTag& ApplicationTag);
	void K2_ActivateAbility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Trap_ZippyTrout_C">();
	}
	static class UGA_Trap_ZippyTrout_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Trap_ZippyTrout_C>();
	}
};
static_assert(alignof(UGA_Trap_ZippyTrout_C) == 0x000008, "Wrong alignment on UGA_Trap_ZippyTrout_C");
static_assert(sizeof(UGA_Trap_ZippyTrout_C) == 0x0009A0, "Wrong size on UGA_Trap_ZippyTrout_C");
static_assert(offsetof(UGA_Trap_ZippyTrout_C, UberGraphFrame_GA_Trap_ZippyTrout_C) == 0x000990, "Member 'UGA_Trap_ZippyTrout_C::UberGraphFrame_GA_Trap_ZippyTrout_C' has a wrong offset!");
static_assert(offsetof(UGA_Trap_ZippyTrout_C, Tag) == 0x000998, "Member 'UGA_Trap_ZippyTrout_C::Tag' has a wrong offset!");

}

