#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCNL_Athena_SkyTube_Loop

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GCNL_Athena_SkyTube_Loop.GCNL_Athena_SkyTube_Loop_C.ExecuteUbergraph_GCNL_Athena_SkyTube_Loop
// 0x0370 (0x0370 - 0x0000)
struct GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable;                                // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_Start;                          // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class USceneComponent*                        CallFunc_K2_GetRootComponent_ReturnValue;          // 0x0010(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetWorldDeltaSeconds_ReturnValue;         // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         Temp_float_Variable;                               // 0x0020(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Temp_float_Variable_1;                             // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_BoolToInt_ReturnValue;               // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_BoolToInt_ReturnValue_1;             // 0x002C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_2;                              // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetVelocity_ReturnValue;                  // 0x0034(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_BoolToInt_ReturnValue_2;             // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USoundBase*                             K2Node_Select_Default;                             // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_BoolToInt_ReturnValue_3;             // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue;           // 0x0058(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             K2Node_Select_Default_1;                           // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_BoolToInt_ReturnValue_4;             // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue_1;         // 0x0070(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsPlayerInVehicle_IsPlayerInVehicle;   // 0x0079(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsPlayerInVehicle_IsPlayerInVehicle_1; // 0x007A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_7B[0x1];                                       // 0x007B(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Select_Default_2;                           // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GetIsPlayerInVehicle_IsPlayerInVehicle_2; // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_81[0x3];                                       // 0x0081(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_FInterpTo_ReturnValue;                    // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue;         // 0x0088(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_ClampVectorSize_ReturnValue;              // 0x0094(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 K2Node_Event_MyTarget_1;                           // 0x00A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 K2Node_Event_Parameters_1;                         // 0x00A8(0x00B8)(ConstParm, ContainsInstancedReference)
	TArray<class UParticleSystemComponent*>       K2Node_Event_ParticleComponents_1;                 // 0x0160(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	TArray<class UAudioComponent*>                K2Node_Event_AudioComponents_1;                    // 0x0170(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	class UCameraShake*                           K2Node_Event_BurstCameraShakeInstance;             // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADecalActor*                            K2Node_Event_BurstDecalInstance;                   // 0x0188(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Normal_ReturnValue;                       // 0x0190(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19C[0x4];                                      // 0x019C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn;             // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x01A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1A9[0x3];                                      // 0x01A9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Dot_VectorVector_ReturnValue;             // 0x01AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MapRangeClamped_ReturnValue;              // 0x01B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B4[0x4];                                      // 0x01B4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAttached_ReturnValue;         // 0x01B8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Dot_VectorVector_ReturnValue_1;           // 0x01C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x01C4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1C5[0x3];                                      // 0x01C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue_1;       // 0x01C8(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Multiply_VectorFloat_ReturnValue_2;       // 0x01D4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             K2Node_Select_Default_3;                           // 0x01E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Abs_ReturnValue;                          // 0x01E8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1EC[0x4];                                      // 0x01EC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue_2;         // 0x01F0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MapRangeClamped_ReturnValue_1;            // 0x01F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1FC[0x4];                                      // 0x01FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AActor*                                 K2Node_Event_MyTarget;                             // 0x0200(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 K2Node_Event_Parameters;                           // 0x0208(0x00B8)(ConstParm, ContainsInstancedReference)
	TArray<class UParticleSystemComponent*>       K2Node_Event_ParticleComponents;                   // 0x02C0(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	TArray<class UAudioComponent*>                K2Node_Event_AudioComponents;                      // 0x02D0(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	class UParticleSystemComponent*               CallFunc_Array_Get_Item;                           // 0x02E0(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x02E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2E9[0x3];                                      // 0x02E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         K2Node_Event_DeltaSeconds;                         // 0x02EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_4;                    // 0x02F0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2F1[0x3];                                      // 0x02F1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x02F4(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0300(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetVelocity_ReturnValue_1;                // 0x030C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VSize_ReturnValue;                        // 0x0318(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_5;                    // 0x031C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31D[0x3];                                      // 0x031D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortSkyTube*                           CallFunc_GetCurrentSkyTube_ReturnValue;            // 0x0320(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0328(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_6;                    // 0x0329(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_32A[0x2];                                      // 0x032A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_FindDirectionClosestToWorldLocation_ReturnValue; // 0x032C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValueAtLevel_ReturnValue;              // 0x0338(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetValueAtLevel_ReturnValue_1;            // 0x033C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MapRangeClamped_ReturnValue_2;            // 0x0340(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_BoolToInt_ReturnValue_5;             // 0x0344(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_BoolToInt_ReturnValue_6;             // 0x0348(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_BoolToInt_ReturnValue_7;             // 0x034C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_GetWorldDeltaSeconds_ReturnValue_1;       // 0x0350(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_GetVelocity_ReturnValue_2;                // 0x0354(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_VSize_ReturnValue_1;                      // 0x0360(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_MapRangeClamped_ReturnValue_3;            // 0x0364(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_FInterpTo_ReturnValue_1;                  // 0x0368(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop) == 0x000008, "Wrong alignment on GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop");
static_assert(sizeof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop) == 0x000370, "Wrong size on GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, EntryPoint) == 0x000000, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::EntryPoint' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_IsValid_ReturnValue) == 0x000004, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, Temp_bool_Variable) == 0x000005, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, Temp_bool_Variable_1) == 0x000006, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_IsValid_ReturnValue_1) == 0x000007, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_CustomEvent_Start) == 0x000008, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_CustomEvent_Start' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_K2_GetRootComponent_ReturnValue) == 0x000010, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_K2_GetRootComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetWorldDeltaSeconds_ReturnValue) == 0x000018, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetWorldDeltaSeconds_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_IsValid_ReturnValue_2) == 0x00001C, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, Temp_float_Variable) == 0x000020, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, Temp_float_Variable_1) == 0x000024, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::Temp_float_Variable_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Conv_BoolToInt_ReturnValue) == 0x000028, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Conv_BoolToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Conv_BoolToInt_ReturnValue_1) == 0x00002C, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Conv_BoolToInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, Temp_bool_Variable_2) == 0x000030, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetVelocity_ReturnValue) == 0x000034, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetVelocity_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Conv_BoolToInt_ReturnValue_2) == 0x000040, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Conv_BoolToInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Select_Default) == 0x000048, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Conv_BoolToInt_ReturnValue_3) == 0x000050, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Conv_BoolToInt_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_SpawnSoundAttached_ReturnValue) == 0x000058, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_SpawnSoundAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Select_Default_1) == 0x000060, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Select_Default_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Conv_BoolToInt_ReturnValue_4) == 0x000068, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Conv_BoolToInt_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_SpawnSoundAttached_ReturnValue_1) == 0x000070, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_SpawnSoundAttached_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_IsValid_ReturnValue_3) == 0x000078, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_IsValid_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetIsPlayerInVehicle_IsPlayerInVehicle) == 0x000079, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetIsPlayerInVehicle_IsPlayerInVehicle' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetIsPlayerInVehicle_IsPlayerInVehicle_1) == 0x00007A, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetIsPlayerInVehicle_IsPlayerInVehicle_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Select_Default_2) == 0x00007C, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Select_Default_2' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetIsPlayerInVehicle_IsPlayerInVehicle_2) == 0x000080, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetIsPlayerInVehicle_IsPlayerInVehicle_2' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_FInterpTo_ReturnValue) == 0x000084, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_FInterpTo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Multiply_VectorFloat_ReturnValue) == 0x000088, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Multiply_VectorFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_ClampVectorSize_ReturnValue) == 0x000094, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_ClampVectorSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_MyTarget_1) == 0x0000A0, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_MyTarget_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_Parameters_1) == 0x0000A8, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_Parameters_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_ParticleComponents_1) == 0x000160, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_ParticleComponents_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_AudioComponents_1) == 0x000170, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_AudioComponents_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_BurstCameraShakeInstance) == 0x000180, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_BurstCameraShakeInstance' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_BurstDecalInstance) == 0x000188, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_BurstDecalInstance' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Normal_ReturnValue) == 0x000190, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Normal_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_DynamicCast_AsFort_Player_Pawn) == 0x0001A0, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_DynamicCast_AsFort_Player_Pawn' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_DynamicCast_bSuccess) == 0x0001A8, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Dot_VectorVector_ReturnValue) == 0x0001AC, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Dot_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_MapRangeClamped_ReturnValue) == 0x0001B0, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_MapRangeClamped_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_SpawnEmitterAttached_ReturnValue) == 0x0001B8, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_SpawnEmitterAttached_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Dot_VectorVector_ReturnValue_1) == 0x0001C0, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Dot_VectorVector_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, Temp_bool_Variable_3) == 0x0001C4, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Multiply_VectorFloat_ReturnValue_1) == 0x0001C8, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Multiply_VectorFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Multiply_VectorFloat_ReturnValue_2) == 0x0001D4, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Multiply_VectorFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Select_Default_3) == 0x0001E0, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Select_Default_3' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Abs_ReturnValue) == 0x0001E8, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Abs_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_SpawnSoundAttached_ReturnValue_2) == 0x0001F0, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_SpawnSoundAttached_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_MapRangeClamped_ReturnValue_1) == 0x0001F8, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_MapRangeClamped_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_MyTarget) == 0x000200, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_MyTarget' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_Parameters) == 0x000208, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_Parameters' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_ParticleComponents) == 0x0002C0, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_ParticleComponents' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_AudioComponents) == 0x0002D0, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_AudioComponents' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Array_Get_Item) == 0x0002E0, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_BooleanAND_ReturnValue) == 0x0002E8, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, K2Node_Event_DeltaSeconds) == 0x0002EC, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::K2Node_Event_DeltaSeconds' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_IsValid_ReturnValue_4) == 0x0002F0, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_IsValid_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_K2_GetActorLocation_ReturnValue) == 0x0002F4, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_K2_GetActorLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Add_VectorVector_ReturnValue) == 0x000300, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Add_VectorVector_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetVelocity_ReturnValue_1) == 0x00030C, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetVelocity_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_VSize_ReturnValue) == 0x000318, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_VSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_IsValid_ReturnValue_5) == 0x00031C, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_IsValid_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetCurrentSkyTube_ReturnValue) == 0x000320, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetCurrentSkyTube_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_BooleanAND_ReturnValue_1) == 0x000328, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_BooleanAND_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_IsValid_ReturnValue_6) == 0x000329, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_IsValid_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_FindDirectionClosestToWorldLocation_ReturnValue) == 0x00032C, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_FindDirectionClosestToWorldLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetValueAtLevel_ReturnValue) == 0x000338, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetValueAtLevel_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetValueAtLevel_ReturnValue_1) == 0x00033C, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetValueAtLevel_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_MapRangeClamped_ReturnValue_2) == 0x000340, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_MapRangeClamped_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Conv_BoolToInt_ReturnValue_5) == 0x000344, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Conv_BoolToInt_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Conv_BoolToInt_ReturnValue_6) == 0x000348, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Conv_BoolToInt_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_Conv_BoolToInt_ReturnValue_7) == 0x00034C, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_Conv_BoolToInt_ReturnValue_7' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetWorldDeltaSeconds_ReturnValue_1) == 0x000350, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetWorldDeltaSeconds_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_GetVelocity_ReturnValue_2) == 0x000354, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_GetVelocity_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_VSize_ReturnValue_1) == 0x000360, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_VSize_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_MapRangeClamped_ReturnValue_3) == 0x000364, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_MapRangeClamped_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop, CallFunc_FInterpTo_ReturnValue_1) == 0x000368, "Member 'GCNL_Athena_SkyTube_Loop_C_ExecuteUbergraph_GCNL_Athena_SkyTube_Loop::CallFunc_FInterpTo_ReturnValue_1' has a wrong offset!");

// Function GCNL_Athena_SkyTube_Loop.GCNL_Athena_SkyTube_Loop_C.ReceiveTick
// 0x0004 (0x0004 - 0x0000)
struct GCNL_Athena_SkyTube_Loop_C_ReceiveTick final
{
public:
	float                                         DeltaSeconds;                                      // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GCNL_Athena_SkyTube_Loop_C_ReceiveTick) == 0x000004, "Wrong alignment on GCNL_Athena_SkyTube_Loop_C_ReceiveTick");
static_assert(sizeof(GCNL_Athena_SkyTube_Loop_C_ReceiveTick) == 0x000004, "Wrong size on GCNL_Athena_SkyTube_Loop_C_ReceiveTick");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_ReceiveTick, DeltaSeconds) == 0x000000, "Member 'GCNL_Athena_SkyTube_Loop_C_ReceiveTick::DeltaSeconds' has a wrong offset!");

// Function GCNL_Athena_SkyTube_Loop.GCNL_Athena_SkyTube_Loop_C.OnLoopingStart
// 0x00E0 (0x00E0 - 0x0000)
struct GCNL_Athena_SkyTube_Loop_C_OnLoopingStart final
{
public:
	class AActor*                                 MyTarget_0;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UParticleSystemComponent*>       ParticleComponents;                                // 0x00C0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
	TArray<class UAudioComponent*>                AudioComponents;                                   // 0x00D0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
};
static_assert(alignof(GCNL_Athena_SkyTube_Loop_C_OnLoopingStart) == 0x000008, "Wrong alignment on GCNL_Athena_SkyTube_Loop_C_OnLoopingStart");
static_assert(sizeof(GCNL_Athena_SkyTube_Loop_C_OnLoopingStart) == 0x0000E0, "Wrong size on GCNL_Athena_SkyTube_Loop_C_OnLoopingStart");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_OnLoopingStart, MyTarget_0) == 0x000000, "Member 'GCNL_Athena_SkyTube_Loop_C_OnLoopingStart::MyTarget_0' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_OnLoopingStart, Parameters) == 0x000008, "Member 'GCNL_Athena_SkyTube_Loop_C_OnLoopingStart::Parameters' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_OnLoopingStart, ParticleComponents) == 0x0000C0, "Member 'GCNL_Athena_SkyTube_Loop_C_OnLoopingStart::ParticleComponents' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_OnLoopingStart, AudioComponents) == 0x0000D0, "Member 'GCNL_Athena_SkyTube_Loop_C_OnLoopingStart::AudioComponents' has a wrong offset!");

// Function GCNL_Athena_SkyTube_Loop.GCNL_Athena_SkyTube_Loop_C.OnRemoval
// 0x00F0 (0x00F0 - 0x0000)
struct GCNL_Athena_SkyTube_Loop_C_OnRemoval final
{
public:
	class AActor*                                 MyTarget_0;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UParticleSystemComponent*>       ParticleComponents;                                // 0x00C0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
	TArray<class UAudioComponent*>                AudioComponents;                                   // 0x00D0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm)
	class UCameraShake*                           BurstCameraShakeInstance;                          // 0x00E0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADecalActor*                            BurstDecalInstance;                                // 0x00E8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GCNL_Athena_SkyTube_Loop_C_OnRemoval) == 0x000008, "Wrong alignment on GCNL_Athena_SkyTube_Loop_C_OnRemoval");
static_assert(sizeof(GCNL_Athena_SkyTube_Loop_C_OnRemoval) == 0x0000F0, "Wrong size on GCNL_Athena_SkyTube_Loop_C_OnRemoval");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_OnRemoval, MyTarget_0) == 0x000000, "Member 'GCNL_Athena_SkyTube_Loop_C_OnRemoval::MyTarget_0' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_OnRemoval, Parameters) == 0x000008, "Member 'GCNL_Athena_SkyTube_Loop_C_OnRemoval::Parameters' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_OnRemoval, ParticleComponents) == 0x0000C0, "Member 'GCNL_Athena_SkyTube_Loop_C_OnRemoval::ParticleComponents' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_OnRemoval, AudioComponents) == 0x0000D0, "Member 'GCNL_Athena_SkyTube_Loop_C_OnRemoval::AudioComponents' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_OnRemoval, BurstCameraShakeInstance) == 0x0000E0, "Member 'GCNL_Athena_SkyTube_Loop_C_OnRemoval::BurstCameraShakeInstance' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_OnRemoval, BurstDecalInstance) == 0x0000E8, "Member 'GCNL_Athena_SkyTube_Loop_C_OnRemoval::BurstDecalInstance' has a wrong offset!");

// Function GCNL_Athena_SkyTube_Loop.GCNL_Athena_SkyTube_Loop_C.Start or Stop Audio
// 0x0001 (0x0001 - 0x0000)
struct GCNL_Athena_SkyTube_Loop_C_Start_or_Stop_Audio final
{
public:
	bool                                          Start;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GCNL_Athena_SkyTube_Loop_C_Start_or_Stop_Audio) == 0x000001, "Wrong alignment on GCNL_Athena_SkyTube_Loop_C_Start_or_Stop_Audio");
static_assert(sizeof(GCNL_Athena_SkyTube_Loop_C_Start_or_Stop_Audio) == 0x000001, "Wrong size on GCNL_Athena_SkyTube_Loop_C_Start_or_Stop_Audio");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_Start_or_Stop_Audio, Start) == 0x000000, "Member 'GCNL_Athena_SkyTube_Loop_C_Start_or_Stop_Audio::Start' has a wrong offset!");

// Function GCNL_Athena_SkyTube_Loop.GCNL_Athena_SkyTube_Loop_C.Init
// 0x0008 (0x0008 - 0x0000)
struct GCNL_Athena_SkyTube_Loop_C_Init final
{
public:
	class AActor*                                 MyTarget_0;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GCNL_Athena_SkyTube_Loop_C_Init) == 0x000008, "Wrong alignment on GCNL_Athena_SkyTube_Loop_C_Init");
static_assert(sizeof(GCNL_Athena_SkyTube_Loop_C_Init) == 0x000008, "Wrong size on GCNL_Athena_SkyTube_Loop_C_Init");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_Init, MyTarget_0) == 0x000000, "Member 'GCNL_Athena_SkyTube_Loop_C_Init::MyTarget_0' has a wrong offset!");

// Function GCNL_Athena_SkyTube_Loop.GCNL_Athena_SkyTube_Loop_C.UpdateIsLocalAndIsPlayer
// 0x0078 (0x0078 - 0x0000)
struct GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer final
{
public:
	class AActor*                                 Target;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x7];                                        // 0x0009(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TScriptInterface<class IFortVehicleInterface> K2Node_DynamicCast_AsFort_Vehicle_Interface;       // 0x0010(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AFortPlayerPawn*>                CallFunc_GetAllPassengers_ReturnValue;             // 0x0028(0x0010)(ZeroConstructor, ReferenceParm)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x003C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_45[0x3];                                       // 0x0045(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn;             // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_52[0x2];                                       // 0x0052(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0054(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue_1;        // 0x0060(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0064(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer) == 0x000008, "Wrong alignment on GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer");
static_assert(sizeof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer) == 0x000078, "Wrong size on GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, Target) == 0x000000, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::Target' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, Temp_bool_True_if_break_was_hit_Variable) == 0x000008, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, K2Node_DynamicCast_AsFort_Vehicle_Interface) == 0x000010, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::K2Node_DynamicCast_AsFort_Vehicle_Interface' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, K2Node_DynamicCast_bSuccess) == 0x000020, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_GetAllPassengers_ReturnValue) == 0x000028, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_GetAllPassengers_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_Not_PreBool_ReturnValue) == 0x000038, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_Array_Length_ReturnValue) == 0x00003C, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_Array_Length_ReturnValue_1) == 0x000040, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_Array_Length_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_Greater_IntInt_ReturnValue) == 0x000044, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, K2Node_DynamicCast_AsFort_Player_Pawn) == 0x000048, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::K2Node_DynamicCast_AsFort_Player_Pawn' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, K2Node_DynamicCast_bSuccess_1) == 0x000050, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_IsLocallyControlled_ReturnValue) == 0x000051, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_IsLocallyControlled_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, Temp_int_Array_Index_Variable) == 0x000054, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_Array_Get_Item) == 0x000058, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_IsLocallyControlled_ReturnValue_1) == 0x000060, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_IsLocallyControlled_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, Temp_int_Loop_Counter_Variable) == 0x000064, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_Less_IntInt_ReturnValue) == 0x000068, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_Add_IntInt_ReturnValue) == 0x00006C, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer, CallFunc_BooleanAND_ReturnValue) == 0x000070, "Member 'GCNL_Athena_SkyTube_Loop_C_UpdateIsLocalAndIsPlayer::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");

// Function GCNL_Athena_SkyTube_Loop.GCNL_Athena_SkyTube_Loop_C.GetIsPlayerInVehicle
// 0x0028 (0x0028 - 0x0000)
struct GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle final
{
public:
	bool                                          IsPlayerInVehicle;                                 // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPawn*                              K2Node_DynamicCast_AsFort_Pawn;                    // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn;             // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsInVehicle_ReturnValue;                  // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle) == 0x000008, "Wrong alignment on GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle");
static_assert(sizeof(GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle) == 0x000028, "Wrong size on GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle, IsPlayerInVehicle) == 0x000000, "Member 'GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle::IsPlayerInVehicle' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle, K2Node_DynamicCast_AsFort_Pawn) == 0x000008, "Member 'GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle::K2Node_DynamicCast_AsFort_Pawn' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle, K2Node_DynamicCast_bSuccess) == 0x000010, "Member 'GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle, CallFunc_IsValid_ReturnValue) == 0x000011, "Member 'GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle, K2Node_DynamicCast_AsFort_Player_Pawn) == 0x000018, "Member 'GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle::K2Node_DynamicCast_AsFort_Player_Pawn' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle, K2Node_DynamicCast_bSuccess_1) == 0x000020, "Member 'GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle, CallFunc_IsInVehicle_ReturnValue) == 0x000021, "Member 'GCNL_Athena_SkyTube_Loop_C_GetIsPlayerInVehicle::CallFunc_IsInVehicle_ReturnValue' has a wrong offset!");

// Function GCNL_Athena_SkyTube_Loop.GCNL_Athena_SkyTube_Loop_C.StartCameraShake
// 0x0028 (0x0028 - 0x0000)
struct GCNL_Athena_SkyTube_Loop_C_StartCameraShake final
{
public:
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0000(0x0010)(ZeroConstructor, NoDestructor)
	class UCameraShake*                           CallFunc_PlayCameraShake_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_DoesImplementInterface_ReturnValue;       // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerController*                  CallFunc_GetFortPlayerControllerFromActor_ReturnValue; // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GCNL_Athena_SkyTube_Loop_C_StartCameraShake) == 0x000008, "Wrong alignment on GCNL_Athena_SkyTube_Loop_C_StartCameraShake");
static_assert(sizeof(GCNL_Athena_SkyTube_Loop_C_StartCameraShake) == 0x000028, "Wrong size on GCNL_Athena_SkyTube_Loop_C_StartCameraShake");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_StartCameraShake, K2Node_CreateDelegate_OutputDelegate) == 0x000000, "Member 'GCNL_Athena_SkyTube_Loop_C_StartCameraShake::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_StartCameraShake, CallFunc_PlayCameraShake_ReturnValue) == 0x000010, "Member 'GCNL_Athena_SkyTube_Loop_C_StartCameraShake::CallFunc_PlayCameraShake_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_StartCameraShake, CallFunc_DoesImplementInterface_ReturnValue) == 0x000018, "Member 'GCNL_Athena_SkyTube_Loop_C_StartCameraShake::CallFunc_DoesImplementInterface_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_StartCameraShake, CallFunc_GetFortPlayerControllerFromActor_ReturnValue) == 0x000020, "Member 'GCNL_Athena_SkyTube_Loop_C_StartCameraShake::CallFunc_GetFortPlayerControllerFromActor_ReturnValue' has a wrong offset!");

// Function GCNL_Athena_SkyTube_Loop.GCNL_Athena_SkyTube_Loop_C.StopCameraShake
// 0x0020 (0x0020 - 0x0000)
struct GCNL_Athena_SkyTube_Loop_C_StopCameraShake final
{
public:
	class AFortPlayerPawn*                        Target;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A[0x2];                                        // 0x000A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x000C(0x0010)(ZeroConstructor, NoDestructor)
};
static_assert(alignof(GCNL_Athena_SkyTube_Loop_C_StopCameraShake) == 0x000008, "Wrong alignment on GCNL_Athena_SkyTube_Loop_C_StopCameraShake");
static_assert(sizeof(GCNL_Athena_SkyTube_Loop_C_StopCameraShake) == 0x000020, "Wrong size on GCNL_Athena_SkyTube_Loop_C_StopCameraShake");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_StopCameraShake, Target) == 0x000000, "Member 'GCNL_Athena_SkyTube_Loop_C_StopCameraShake::Target' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_StopCameraShake, CallFunc_IsValid_ReturnValue) == 0x000008, "Member 'GCNL_Athena_SkyTube_Loop_C_StopCameraShake::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_StopCameraShake, CallFunc_IsValid_ReturnValue_1) == 0x000009, "Member 'GCNL_Athena_SkyTube_Loop_C_StopCameraShake::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GCNL_Athena_SkyTube_Loop_C_StopCameraShake, K2Node_CreateDelegate_OutputDelegate) == 0x00000C, "Member 'GCNL_Athena_SkyTube_Loop_C_StopCameraShake::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");

}

