#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SettingsListEntry_KeyboardInput

#include "Basic.hpp"

#include "SettingsListEntry_KeyboardInput_classes.hpp"
#include "SettingsListEntry_KeyboardInput_parameters.hpp"


namespace SDK
{

// Function SettingsListEntry_KeyboardInput.SettingsListEntry_KeyboardInput_C.OnUpdateKeyText
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// class FText                             PrimaryKeyText                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// class FText                             SecondaryKeyText                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USettingsListEntry_KeyboardInput_C::OnUpdateKeyText(const class FText& PrimaryKeyText, const class FText& SecondaryKeyText)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsListEntry_KeyboardInput_C", "OnUpdateKeyText");

	Params::SettingsListEntry_KeyboardInput_C_OnUpdateKeyText Parms{};

	Parms.PrimaryKeyText = std::move(PrimaryKeyText);
	Parms.SecondaryKeyText = std::move(SecondaryKeyText);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SettingsListEntry_KeyboardInput.SettingsListEntry_KeyboardInput_C.ExecuteUbergraph_SettingsListEntry_KeyboardInput
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USettingsListEntry_KeyboardInput_C::ExecuteUbergraph_SettingsListEntry_KeyboardInput(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("SettingsListEntry_KeyboardInput_C", "ExecuteUbergraph_SettingsListEntry_KeyboardInput");

	Params::SettingsListEntry_KeyboardInput_C_ExecuteUbergraph_SettingsListEntry_KeyboardInput Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

